#!/bin/perl

use warnings;
use Time::Moment;

if(@ARGV != 2) {
    print "Usage: ex11-2 <year> <month>\n";
    exit;
}

my $dt1 = Time::Moment->now;
my $dt2 = Time::Moment->new(
            year   => $ARGV[0],
            month  => $ARGV[1],
            day    => 1,
);

if($dt1 > $dt2) {
    ($dt1, $dt2) = ($dt2, $dt1);
}

my $years  = $dt1->delta_years ( $dt2 );
my $months = $dt1->delta_months( $dt2 ) % 12;
my $days   = $dt1->delta_days( $dt2 )   % 365;

printf "%d years, %d months, and %d days\n", $years, $months, $days;
