#!/bin/perl 

use strict;

sub total () {
    my $sum = 0;
    foreach (@_) {
        $sum += $_;
    }
    $sum;
}

sub test_total () {
    my $sum = &total(@_);
    print "Sum of (@_) is $sum.\n";
}


&test_total(0,1,2);
&test_total(1,3,5,7,9);
&test_total();

