#!/bin/perl 

use strict;

sub total () {
    my $sum = 0;
    foreach (@_) {
        $sum += $_;
    }
    $sum;
}

sub average () {
    if(@_ != 0) {
        &total(@_) / @_;
    } else {
        print "Warning: average : Empty array Passed\n";
        undef;
    }
}

sub above_average() {
    my $average = &average(@_);
    my @more_than_average;
    foreach (@_) {
        if( $_ >= $average) {
            push @more_than_average, $_;
        }
    }
    @more_than_average;
}

sub test_average () {
    my $average = &average(@_);
    if(@_ <= 10) {
        print "Average of (@_) is $average.\n";
    } else {
        print "Average is $average.\n";
    }
}

sub test_above_average () {
    my @above = &above_average(@_);
    if(@_ <= 20) {
        print "Above Average in (@_) are (@above).\n";
    } else {
        print "Above Average is (@above).\n";
    }
}

&test_above_average(1..10);
&test_above_average(100, 1..10);
&test_above_average();
&test_above_average(10);
&test_above_average(10,10);
&test_above_average(1);


