#!/bin/perl

use warnings;
use v5.10;

my $debug = $ENV{PERL_DEBUG} // 1;

my $secret_number = int(1 + rand 100);
print ("DEBUG : secret_number selected is $secret_number\n") if $debug;

$attempts = 0;
print "Guess the number b/w 1-100 (or quit/exit to end the game):";
while(<STDIN>) {
    chomp;
    ++$attempts;

    if(/exit|quit/i) {
        print "Exiting...\n";
        last;
    }
    if(/\D+/) {
        print "Not a number $_. Try again...\n";
        --$attempts;
        next;
    }

    if($_ == $secret_number) {
        print "Yes!!! you are correct, it took you only $attempts attempts\n";
        last;
    } elsif ($_ < $secret_number) {
        print "Too Low!!! Try higher\n";
    } else {
        print "Too High!!! Try lower\n";
    }
}
