#!/bin/perl

use v5.10;
use warnings;

while(<>) {
    chomp;
    if(/(?<word>(\w*)a)\b/) {
        print "Matched: |$`<$&>$'|\n";
        print "word contains $+{word}\n";
    }
    else {
        print "No match: $_\n";
    }
}
