#!/bin/perl
use warnings;

$max_column_width = 75;

$longest_value_width = 0;
foreach (values %ENV) {
    if(length($_) > $longest_value_width) {
        $longest_value_width = length($_);
    }
    if($longest_value_width >= $max_column_width) {
        $longest_value_width = $max_column_width;
        last;
    }
}

$longest_key_width = 0;
foreach (keys %ENV) {
    if(length($_) > $longest_key_width) {
        $longest_key_width = length($_);
    }
    if($longest_key_width >= $max_column_width) {
        $longest_key_width = $max_column_width;
        last;
    }
}

while( ($key, $value) = each %ENV) {
    printf "%${longest_key_width}s  : %${longest_value_width}s\n", $key, $value;
}
